COLOR_RED = "|cFFFE346E"
COLOR_BLUE = "|cFF4A79FC"

FACTION_ALIANCE = 1
FACTION_HORDE = 2
ALL_FACTIONS = {FACTION_ALIANCE, FACTION_HORDE}

BATTLEFIELD_NONE = 0 --{id = 0, locale = "BATTLEFIELD_NONE", name = "None"}
BATTLEFIELD_WARSONG = 489 --{id = 489, locale = "BATTLEFIELD_WARSONG", name = "Warsong"}
BATTLEFIELD_ARATHI = 529 --{id = 529, locale = "BATTLEFIELD_ARATHI", name = "Arathi"}
BATTLEFIELD_ALTERAC = 30 --{id = 30, locale = "BATTLEFIELD_ALTERAC", name = "Alterac"}
ALL_BATTLEFIELDS = {BATTLEFIELD_WARSONG, BATTLEFIELD_ARATHI, BATTLEFIELD_ALTERAC}

MOUSE_BUTTON_LEFT = "LeftButton"
MOUSE_BUTTON_MIDDLE = "MiddleButton"
MOUSE_BUTTON_RIGHT = "RightButton"

CHAT_PRINT = 0
CHAT_SAY = 1
CHAT_YELLOW = 2
CHAT_PARTY = 3
CHAT_GUILD = 4
